"""Generate and validate the searchable MkDocs bibliography index."""

from __future__ import annotations

import argparse
from pathlib import Path

from quviz.docs.bibliography import BibEntry, Bibliography, Person, parse_bibtex_file
from quviz.docs.pins import validate_source_pins
from quviz.docs.scan import cited_keys_in_tree

ROOT = Path(__file__).resolve().parents[1]
BIB_PATH = ROOT / "references.bib"
OUTPUT_PATH = ROOT / "docs" / "references" / "index.md"
# Entries that document the build toolchain rather than a scientific claim are
# not expected to appear in prose.
TOOLING_KEYWORD = "tooling"


def person_name(person: Person) -> str:
    if person.literal:
        return person.literal
    first = " ".join(person.first_names)
    last = " ".join(person.last_names)
    return ", ".join(part for part in (last, first) if part)


def format_authors(entry: BibEntry) -> str:
    if entry.authors:
        return "; ".join(person_name(person) for person in entry.authors)
    return entry.fields.get("organization", "Unknown")


def links(entry: BibEntry) -> str:
    values: list[str] = []
    doi = entry.fields.get("doi")
    url = entry.fields.get("url")
    if doi:
        values.append(f"[DOI](https://doi.org/{doi})")
    if url:
        values.append(f"[source]({url})")
    return " · ".join(values)


def section_name(entry: BibEntry) -> str:
    keywords = {value.strip() for value in entry.fields.get("keywords", "").split(",")}
    if "source-audit" in keywords:
        return "Audited source material"
    if "experiment" in keywords or "measurement" in keywords:
        return "Experiments and measurement"
    if "chemistry" in keywords or "symmetry" in keywords:
        return "Symmetry and chemical interpretation"
    if "software" in keywords:
        return "Software and numerical infrastructure"
    if "visualization" in keywords or "education" in keywords:
        return "Visualization and teaching"
    return "Physics and mathematics"


def render(bibliography: Bibliography) -> str:
    grouped: dict[str, list[tuple[str, BibEntry]]] = {}
    for key, entry in bibliography.entries.items():
        grouped.setdefault(section_name(entry), []).append((key, entry))

    lines = [
        "<!-- Generated by scripts/render_reference_index.py; do not edit manually. -->",
        "# Citation index",
        "",
        "`references.bib` is the canonical machine-readable source. Documentation citations use",
        "Pandoc-like keys such as `[\\@stodolna2013stark]`; the MkDocs extension validates and",
        "renders them as author-year labels.",
        "",
    ]
    order = [
        "Physics and mathematics",
        "Experiments and measurement",
        "Symmetry and chemical interpretation",
        "Visualization and teaching",
        "Audited source material",
        "Software and numerical infrastructure",
    ]
    for section in order:
        entries = grouped.get(section, [])
        if not entries:
            continue
        lines.extend([f"## {section}", ""])
        for key, entry in sorted(entries, key=lambda item: item[0]):
            title = entry.fields.get("title", key)
            year = entry.fields.get("year", "n.d.")
            venue = (
                entry.fields.get("journal")
                or entry.fields.get("booktitle")
                or entry.fields.get("publisher", "")
            )
            link_text = links(entry)
            author_text = format_authors(entry).rstrip(".")
            year_text = year if year.endswith(".") else f"{year}."
            lines.extend(
                [
                    f'<a id="{key}"></a>',
                    f"### `{key}` — {title}",
                    "",
                    f"**{author_text}.** {year_text}" + (f" *{venue}*." if venue else ""),
                    "",
                    link_text,
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def cited_keys(docs_dir: Path = ROOT / "docs", output_path: Path = OUTPUT_PATH) -> set[str]:
    """Keys cited in documentation prose -- code blocks and comments excluded."""

    try:
        return cited_keys_in_tree(docs_dir, exclude=(output_path,))
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc


def orphan_keys(bibliography: Bibliography, used: set[str]) -> list[str]:
    """Entries nobody cites, and which therefore nobody reviews."""

    return sorted(
        key
        for key, entry in bibliography.entries.items()
        if key not in used
        and TOOLING_KEYWORD
        not in {value.strip() for value in entry.fields.get("keywords", "").split(",")}
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    # Overridable so the gate itself can be tested against a throwaway tree.
    parser.add_argument("--bib", type=Path, default=BIB_PATH)
    parser.add_argument("--docs", type=Path, default=ROOT / "docs")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()
    output_path: Path = args.output

    bibliography = parse_bibtex_file(args.bib)
    used = cited_keys(args.docs, output_path)
    missing = used - set(bibliography.entries)
    if missing:
        raise SystemExit(f"unknown documentation citation keys: {sorted(missing)}")
    orphans = orphan_keys(bibliography, used)
    if orphans:
        raise SystemExit(
            f"orphan bibliography entries (cited nowhere, tag `keywords = {{tooling}}` "
            f"if that is intended): {orphans}"
        )
    pin_problems = validate_source_pins(bibliography.entries.values())
    if pin_problems:
        details = "\n  ".join(pin_problems)
        raise SystemExit(f"source-audit pins are missing or incoherent:\n  {details}")

    rendered = render(bibliography)
    if args.check:
        current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if current != rendered:
            raise SystemExit("reference index is stale; run scripts/render_reference_index.py")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
