"""Generate and validate the searchable MkDocs bibliography index."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from quviz.docs.bibliography import BibEntry, Bibliography, Person, keywords, parse_bibtex_file
from quviz.docs.pins import validate_source_pins
from quviz.docs.scan import cited_keys_in_tree, orphan_keys

ROOT = Path(__file__).resolve().parents[1]
BIB_PATH = ROOT / "references.bib"
DOCS_DIR = ROOT / "docs"
OUTPUT_PATH = DOCS_DIR / "references" / "index.md"


def person_name(person: Person) -> str:
    if person.literal:
        return person.literal
    first = " ".join(person.first_names)
    last = " ".join(person.last_names)
    return ", ".join(part for part in (last, first) if part)


def format_authors(entry: BibEntry) -> str:
    if entry.authors:
        return "; ".join(person_name(person) for person in entry.authors)
    return entry.fields.get("organization", "Unknown")


def links(entry: BibEntry) -> str:
    values: list[str] = []
    doi = entry.fields.get("doi")
    url = entry.fields.get("url")
    if doi:
        values.append(f"[DOI](https://doi.org/{doi})")
    if url:
        values.append(f"[source]({url})")
    return " · ".join(values)


def section_name(entry: BibEntry) -> str:
    tags = keywords(entry)
    if "source-audit" in tags:
        return "Audited source material"
    if "experiment" in tags or "measurement" in tags:
        return "Experiments and measurement"
    if "chemistry" in tags or "symmetry" in tags:
        return "Symmetry and chemical interpretation"
    if "software" in tags:
        return "Software and numerical infrastructure"
    if "visualization" in tags or "education" in tags:
        return "Visualization and teaching"
    return "Physics and mathematics"


def render(bibliography: Bibliography) -> str:
    grouped: dict[str, list[tuple[str, BibEntry]]] = {}
    for key, entry in bibliography.entries.items():
        grouped.setdefault(section_name(entry), []).append((key, entry))

    lines = [
        "<!-- Generated by scripts/render_reference_index.py; do not edit manually. -->",
        "# Citation index",
        "",
        "`references.bib` is the canonical machine-readable source. Documentation citations use",
        "Pandoc-like keys such as `[@stodolna2013stark]`; the MkDocs extension validates and",
        "renders them as author-year labels.",
        "",
    ]
    order = [
        "Physics and mathematics",
        "Experiments and measurement",
        "Symmetry and chemical interpretation",
        "Visualization and teaching",
        "Audited source material",
        "Software and numerical infrastructure",
    ]
    for section in order:
        entries = grouped.get(section, [])
        if not entries:
            continue
        lines.extend([f"## {section}", ""])
        for key, entry in sorted(entries, key=lambda item: item[0]):
            title = entry.fields.get("title", key)
            year = entry.fields.get("year", "n.d.")
            venue = (
                entry.fields.get("journal")
                or entry.fields.get("booktitle")
                or entry.fields.get("publisher", "")
            )
            link_text = links(entry)
            author_text = format_authors(entry).rstrip(".")
            year_text = year if year.endswith(".") else f"{year}."
            lines.extend(
                [
                    f'<a id="{key}"></a>',
                    f"### `{key}` — {title}",
                    "",
                    f"**{author_text}.** {year_text}" + (f" *{venue}*." if venue else ""),
                    "",
                    link_text,
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def cited_keys() -> set[str]:
    """Keys cited in documentation prose -- code blocks and comments excluded."""

    try:
        return cited_keys_in_tree(DOCS_DIR, exclude=(OUTPUT_PATH,))
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc


def write_index(path: Path, rendered: str) -> None:
    """Write the index with LF line endings regardless of platform.

    A text-mode write on Windows would turn every LF into CRLF, and the
    byte-level docs gate (``tests/test_docs_integrity.py``) rejects any CR.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)


def index_is_current(path: Path, rendered: str) -> bool:
    """Byte-for-byte comparison, so a CRLF copy of the right text is stale."""

    return path.exists() and path.read_bytes() == rendered.encode("utf-8")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    bibliography = parse_bibtex_file(BIB_PATH)
    used = cited_keys()
    missing = used - set(bibliography.entries)
    if missing:
        raise SystemExit(f"unknown documentation citation keys: {sorted(missing)}")
    orphans = orphan_keys(bibliography, used)
    if orphans:
        raise SystemExit(
            f"orphan bibliography entries (cited nowhere, tag `keywords = {{tooling}}` "
            f"if that is intended): {orphans}"
        )
    pin_problems = validate_source_pins(bibliography.entries.values())
    if pin_problems:
        details = "\n  ".join(pin_problems)
        raise SystemExit(f"source-audit pins are missing or incoherent:\n  {details}")

    rendered = render(bibliography)
    if args.check:
        if not index_is_current(OUTPUT_PATH, rendered):
            raise SystemExit("reference index is stale; run scripts/render_reference_index.py")
        return 0

    write_index(OUTPUT_PATH, rendered)
    print(OUTPUT_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
